return {
    'angular-language-server',
    'astro-language-server',
    'biome',
    'css-lsp',
    'docker-compose-language-service',
    'dockerfile-language-server',
    'emmet-ls',
    'eslint-lsp',
    'eslint_d',
    'html-lsp',
    'htmx-lsp',
    'json-lsp',
    'lua-language-server',
    'prettier',
    'prettierd',
    'pyright',
    'stylua',
    'tailwindcss-language-server',
    'typescript-language-server',
    'vetur-vls',
    'yaml-language-server',
}

